import { registerUiMessages, type UiMessageParams, type UiMessageValue } from '@/lib/uiMessages'

export const worldModelZhMessages = {
  'worldModel.common.all': '全部',
  'worldModel.common.entities': '实体',
  'worldModel.common.relationships': '关系',
  'worldModel.common.systems': '体系',
  'worldModel.common.draftReview': '草稿审核',
  'worldModel.common.view': '查看',
  'worldModel.common.locate': '定位',
  'worldModel.common.reject': '拒绝',
  'worldModel.common.retry': '重试',
  'worldModel.common.processing': '处理中...',
  'worldModel.common.file': '文件',
  'worldModel.common.pack': '包',
  'worldModel.common.notes': '注意事项',
  'worldModel.common.created': '新增',
  'worldModel.common.updated': '更新',
  'worldModel.common.deleted': '删除',
  'worldModel.common.none': '无',
  'worldModel.common.remove': '移除',
  'worldModel.common.visibility': '可见性',
  'worldModel.common.description': '描述',
  'worldModel.common.aliases': '别名',
  'worldModel.common.unknownNode': '未知节点',
  'worldModel.common.unnamedNode': ({ index }) => `未命名节点 ${String(index ?? 0)}`,
  'worldModel.common.searchDrafts': '搜索草稿...',
  'worldModel.common.searchEntities': '搜索实体...',
  'worldModel.common.searchSystems': '搜索体系...',

  'worldModel.atlas.returnToStudio': '返回工作台',
  'worldModel.atlas.reviewTab': '草稿审核',
  'worldModel.atlas.startEditingSystem': '选择一个体系开始编辑',

  'worldModel.entity.new': '+ 新实体',
  'worldModel.entity.defaultName': '新实体',
  'worldModel.entity.empty': '选择一个实体查看详情',
  'worldModel.entity.delete': '删除实体',
  'worldModel.entity.deleteConfirm': '确定要删除这个实体吗？删除后无法恢复。',
  'worldModel.entity.description': '描述',
  'worldModel.entity.aliases': '别名',
  'worldModel.entity.noAliases': '（暂无别名）',
  'worldModel.entity.addAliasPlaceholder': '添加别名...',
  'worldModel.entity.addAlias': '添加',
  'worldModel.entity.attributes': '属性',
  'worldModel.entity.addAttribute': '+ 添加属性',
  'worldModel.entity.column.name': '属性名',
  'worldModel.entity.column.surface': '表层',
  'worldModel.entity.column.truth': '真相',
  'worldModel.entity.column.visibility': '可见',
  'worldModel.entity.customTypePlaceholder': '自定义类型...',

  'worldModel.relationship.empty': '选择一个实体查看关系',
  'worldModel.relationship.new': '创建关系',
  'worldModel.relationship.fromTo': ({ source, target }) => `从 ${String(source ?? '')} 到 ${String(target ?? '')}`,
  'worldModel.relationship.selectTargetFallback': '（请选择目标实体）',
  'worldModel.relationship.searchTargetPlaceholder': '搜索目标实体...',
  'worldModel.relationship.noMatchingTargets': '没有匹配的目标实体',
  'worldModel.relationship.labelPlaceholder': '关系标签',

  'worldModel.system.new': '+ 新体系',
  'worldModel.system.back': '‹ 世界体系',
  'worldModel.system.delete': '删除体系',
  'worldModel.system.deleteConfirm': '确认删除？',
  'worldModel.system.searchPlaceholder': '搜索体系...',
  'worldModel.system.namePlaceholder': '体系名称',
  'worldModel.system.unsupportedType': '当前体系类型无法编辑，请检查数据是否已经迁移。',
  'worldModel.system.rejectAllTitle': '拒绝全部草稿体系？',
  'worldModel.system.rejectAllDescription': ({ count }) => `将删除 ${String(count ?? 0)} 个草稿体系。\n此操作不可撤销。`,
  'worldModel.system.rejectAllConfirm': '拒绝并删除',
  'worldModel.system.display.hierarchy': '层级结构',
  'worldModel.system.display.timeline': '时间线',
  'worldModel.system.display.list': '列表',
  'worldModel.system.display.graph': '关系图（只读）',

  'worldModel.legacyGraph.notice': '这是旧版关系图体系。当前版本仅保留读取兼容，不再支持新建或编辑图结构；如需继续维护，请迁移到关系或列表/层级体系。',
  'worldModel.legacyGraph.nodes': ({ count }) => `节点 (${String(count ?? 0)})`,
  'worldModel.legacyGraph.edges': ({ count }) => `连线 (${String(count ?? 0)})`,
  'worldModel.legacyGraph.emptyNodes': '没有可展示的节点。',
  'worldModel.legacyGraph.emptyEdges': '没有可展示的连线。',

  'worldModel.bootstrap.extractFromChapters': '从章节提取',
  'worldModel.bootstrap.reextractDrafts': '重新提取草稿',
  'worldModel.bootstrap.failed': '执行失败',
  'worldModel.bootstrap.completedIndexRefresh': '全书检索已更新',
  'worldModel.bootstrap.summaryCounts': ({ entities, relationships }) => `${String(entities ?? 0)} 实体 · ${String(relationships ?? 0)} 关系`,
  'worldModel.bootstrap.confirmTitle': '危险操作：重新提取章节草稿',
  'worldModel.bootstrap.confirmDescription': '替换当前从章节提取的草稿（保留已确认内容），然后重新提取实体和关系。\n确认继续吗？',
  'worldModel.bootstrap.confirmAction': '确认重新提取',
  'worldModel.bootstrap.step.pending': '准备中',
  'worldModel.bootstrap.step.tokenizing': '分词处理',
  'worldModel.bootstrap.step.extracting': '提取候选词',
  'worldModel.bootstrap.step.windowing': '分析章节关联',
  'worldModel.bootstrap.step.refining': 'AI 精炼提取',
  'worldModel.bootstrap.noText': '请先上传章节内容',
  'worldModel.bootstrap.triggerFailed': '操作失败，请重试',

  'worldModel.windowIndex.bootstrap.preparingContent': '正在准备全书内容',
  'worldModel.windowIndex.bootstrap.organizingChapters': '正在整理章节内容',
  'worldModel.windowIndex.bootstrap.ready': '已可从全书中查找线索',
  'worldModel.windowIndex.bootstrap.pendingSync': '章节更新后待同步',
  'worldModel.windowIndex.bootstrap.missing': '还在准备全书内容',
  'worldModel.windowIndex.bootstrap.failed': '全书检索暂不可用',
  'worldModel.windowIndex.copilot.preparingContent': '正在准备全书内容。',
  'worldModel.windowIndex.copilot.organizingContent': '章节有更新，正在整理全书内容；当前会先参考最近几章。',
  'worldModel.windowIndex.copilot.ready': '已可直接跨章节查找设定、人物与线索。',
  'worldModel.windowIndex.copilot.pendingSync': '章节有更新，正在同步全书内容；当前会先参考最近几章。',
  'worldModel.windowIndex.copilot.missing': '全书内容还在准备中；当前会先参考最近几章。',
  'worldModel.windowIndex.copilot.failed': '全书内容暂时整理失败；当前会先参考最近几章。',

  'worldModel.generate.title': '从设定生成',
  'worldModel.generate.description': '粘贴世界观设定文本，生成草稿后进入「草稿审核」确认。',
  'worldModel.generate.placeholder': '在这里粘贴世界观设定（例如：世界规则、阵营、人物关系、力量体系…）',
  'worldModel.generate.minLength': ({ count }) => `至少 ${String(count ?? 0)} 个非空白字符`,
  'worldModel.generate.tooLong': '已超过上限',
  'worldModel.generate.submit': '生成',
  'worldModel.generate.submitting': '生成中...',
  'worldModel.generate.importLink': '已有世界观文件？直接导入',
  'worldModel.generate.importing': '导入中...',
  'worldModel.generate.inputInvalid': '输入不符合要求，请检查长度',
  'worldModel.generate.serviceUnavailable': 'AI 服务不可用，请检查模型配置或稍后重试',
  'worldModel.generate.schemaInvalid': 'AI 输出解析失败，请重试',
  'worldModel.generate.conflict': '生成冲突，请稍后重试',
  'worldModel.generate.failed': '生成失败，请重试',
  'worldModel.generate.fileUnsupported': '文件格式不支持，请使用正确的世界观文件',
  'worldModel.generate.fileUnreadable': '文件内容无法识别，请检查文件格式',
  'worldModel.generate.validation.maxChars': ({ count }) => `最多输入 ${String(count ?? 0)} 个字符`,
  'worldModel.generate.validation.minChars': ({ count }) => `请至少输入 ${String(count ?? 0)} 个非空白字符`,

  'worldModel.worldpack.title': '导入世界观',
  'worldModel.worldpack.subtitle': '上传世界观文件',
  'worldModel.worldpack.selectAndImport': '选择文件并导入',
  'worldModel.worldpack.import': '导入',
  'worldModel.worldpack.importing': '正在导入...',
  'worldModel.worldpack.completed': '世界观导入完成',
  'worldModel.worldpack.failed': '世界观导入失败，请重试',
  'worldModel.worldpack.fileUnsupported': '文件格式不支持，请使用正确的世界观文件',
  'worldModel.worldpack.fileUnreadable': '文件内容无法识别，请检查文件格式',

  'worldModel.draftReview.noMatches': '没有匹配项',
  'worldModel.draftReview.noDrafts': '暂无草稿',
  'worldModel.draftReview.viewAll': '查看全部 →',
  'worldModel.draftReview.rejectAndDelete': '拒绝并删除',
  'worldModel.draftReview.rejectAllTitle': ({ kind }) => `拒绝全部${String(kind ?? '')}？`,
  'worldModel.draftReview.rejectAllDescription': ({ count, kind }) => `将删除 ${String(count ?? 0)} 个草稿${String(kind ?? '')}。\n此操作不可撤销。`,

  'worldModel.onboarding.title': '先构建世界观，再开始写作',
  'worldModel.onboarding.description': '你可以从设定文本生成草稿，或从章节中自动提取实体与关系。',
  'worldModel.onboarding.generateTitle': '从设定生成',
  'worldModel.onboarding.generateDescription': '粘贴世界观设定，让 AI 提取实体、关系与体系草稿，然后你再逐条确认。',
  'worldModel.onboarding.extractTitle': '从章节提取',
  'worldModel.onboarding.extractDescription': '从已上传的章节内容中自动提取实体与关系草稿。',
  'worldModel.onboarding.dismiss': '前往世界模型页稍后添加 →',
} as const satisfies Record<string, UiMessageValue>

export const continuationZhMessages = {
  // -- Continuation Setup Stage --
  'continuation.setup.basedOn': ({ chapter }: UiMessageParams) => `基于${String(chapter ?? '')}继续`,
  'continuation.setup.charCount': ({ count }: UiMessageParams) => `${String(count ?? 0)} 字`,
  'continuation.setup.loadingChapter': '加载章节内容...',
  'continuation.setup.emptyChapter': '章节暂无内容',
  'continuation.setup.title': '续写设置',
  'continuation.setup.instruction': '续写指令（可选）',
  'continuation.setup.instructionPlaceholder': '描述你想要的情节走向，或留空让 AI 自由续写',
  'continuation.setup.length': '续写长度',
  'continuation.setup.advancedSettings': '高级设置',
  'continuation.setup.contextChapters': '上下文章节数',
  'continuation.setup.numVersions': '生成版本数',
  'continuation.setup.temperature': '创意温度',
  'continuation.setup.generate': '生成续写',

  // -- Continuation Results Stage --
  'continuation.results.loading': '正在加载续写结果...',
  'continuation.results.retry': '重试',
  'continuation.results.back': '返回',
  'continuation.results.noResults': '未找到续写结果，请从工作区重新生成。',
  'continuation.results.returnToWorkspace': '返回工作区',
  'continuation.results.quotaExhausted': '生成额度已用完',
  'continuation.results.serviceBusy': '当前使用人数较多，请稍后再试',
  'continuation.results.requestFailed': ({ status }: UiMessageParams) => `请求失败（HTTP ${String(status ?? '')})`,
  'continuation.results.quotaFeedback': '提交使用反馈即可获得额外生成额度，立即继续创作。',
  'continuation.results.submitFeedbackUnlock': '提交反馈，解锁额度',
  'continuation.results.feedbackAlreadyClaimed': '反馈额度已领取。你可以在设置中配置自己的 API Key 继续使用。',
  'continuation.results.goToSettings': '前往设置',
  'continuation.results.badge': '续写结果',
  'continuation.results.continuationOf': ({ chapter }: UiMessageParams) => `${String(chapter ?? '')}续写`,
  'continuation.results.generating': '生成中',
  'continuation.results.adopt': '采纳此版本',
  'continuation.results.regenerate': '重新生成',
  'continuation.results.exportAll': '导出全部',
  'continuation.results.version': ({ n }: UiMessageParams) => `版本 ${String(n ?? '')}`,
  'continuation.results.injectionSummary': ({ entities, relationships, systems }: UiMessageParams) =>
    `注入摘要(${String(entities ?? 0)} 个实体,${String(relationships ?? 0)} 个关系,${String(systems ?? 0)} 个系统)`,
  'continuation.results.emptyContent': '暂无内容',
  'continuation.results.exportVersionHeader': ({ n }: UiMessageParams) => `========== 版本 ${String(n ?? '')} ==========`,

  // -- Chapter Editor --
  'editor.undo': '撤销',
  'editor.redo': '重做',
  'editor.driftWarning': '漂移警告',
  'editor.charCount': ({ count }: UiMessageParams) => `${String(count ?? 0)} 字`,
  'editor.cursorPosition': ({ para, col }: UiMessageParams) => `第 ${String(para ?? 0)} 段 · 第 ${String(col ?? 0)} 列`,
  'editor.autoSaved': '已自动保存',
  'editor.unsaved': '未保存更改',
  'editor.save': '保存',

  // -- Drift Warning Popover --
  'drift.unknownTerm': '未知名词',
  'drift.unknownNaming': '未知称谓',
  'drift.unknownDefault': '未知词汇',
  'drift.dismiss': '忽略',

  // -- Prose Warnings Panel --
  'prose.repeatedNgram': '重复短语',
  'prose.longParagraph': '段落过长',
  'prose.abnormalSentenceLength': '句子过长',
  'prose.summaryTone': '总结式语气',
  'prose.checkTitle': ({ count }: UiMessageParams) => `文本质量检查（${String(count ?? 0)} 项提示）`,
  'prose.itemCount': ({ count }: UiMessageParams) => `${String(count ?? 0)} 项`,
  'prose.candidate': ({ n }: UiMessageParams) => `候选 ${String(n ?? '')}`,

  // -- Studio Page (continuation-path strings) --
  'studio.chapter.deleteConfirm': ({ chapter }: UiMessageParams) => `确定要删除${String(chapter ?? '')}吗？此操作无法撤销。`,
  'studio.chapter.editing': '编辑中',
  'studio.chapter.reading': '阅读中',
  'studio.chapter.titlePlaceholder': '输入章节标题',
  'studio.chapter.titleEditHint': '双击编辑标题',
  'studio.chapter.titleAddHint': '双击添加标题',
  'studio.header.workspace': '章节工作台',
  'studio.header.selectChapter': '选择章节',
  'studio.actions.moreActions': '更多操作',
  'studio.actions.exportAllChapters': '导出全部章节',
  'studio.loading': '加载中...',
  'studio.novelNotFound': '作品不存在',
  'studio.chapter.charCount': ({ count }: UiMessageParams) => `${String(count ?? 0)} 字`,
  'studio.chapter.updated': ({ time }: UiMessageParams) => `${String(time ?? '')}更新`,
  'studio.chapter.edit': '编辑',
  'studio.chapter.delete': '删除章节',
} as const satisfies Record<string, UiMessageValue>
export const novelZhMessages = {
  ...worldModelZhMessages,
  ...continuationZhMessages,
} as const satisfies Record<string, UiMessageValue>

export const novelEnMessages = {
  'worldModel.common.all': 'All',
  'worldModel.common.entities': 'Entities',
  'worldModel.common.relationships': 'Relationships',
  'worldModel.common.systems': 'Systems',
  'worldModel.common.draftReview': 'Draft review',
  'worldModel.common.view': 'View',
  'worldModel.common.locate': 'Locate',
  'worldModel.common.reject': 'Reject',
  'worldModel.common.retry': 'Retry',
  'worldModel.common.processing': 'Processing...',
  'worldModel.common.file': 'File',
  'worldModel.common.pack': 'Pack',
  'worldModel.common.notes': 'Notes',
  'worldModel.common.created': 'Created',
  'worldModel.common.updated': 'Updated',
  'worldModel.common.deleted': 'Deleted',
  'worldModel.common.none': 'None',
  'worldModel.common.remove': 'Remove',
  'worldModel.common.visibility': 'Visibility',
  'worldModel.common.description': 'Description',
  'worldModel.common.aliases': 'Aliases',
  'worldModel.common.unknownNode': 'Unknown node',
  'worldModel.common.unnamedNode': ({ index }) => `Unnamed node ${String(index ?? 0)}`,
  'worldModel.common.searchDrafts': 'Search drafts...',
  'worldModel.common.searchEntities': 'Search entities...',
  'worldModel.common.searchSystems': 'Search systems...',

  'worldModel.atlas.returnToStudio': 'Return to Studio',
  'worldModel.atlas.reviewTab': 'Draft review',
  'worldModel.atlas.startEditingSystem': 'Select a system to start editing',

  'worldModel.entity.new': '+ New entity',
  'worldModel.entity.defaultName': 'New entity',
  'worldModel.entity.empty': 'Select an entity to view details',
  'worldModel.entity.delete': 'Delete entity',
  'worldModel.entity.deleteConfirm': 'Delete this entity? This cannot be undone.',
  'worldModel.entity.description': 'Description',
  'worldModel.entity.aliases': 'Aliases',
  'worldModel.entity.noAliases': '(No aliases yet)',
  'worldModel.entity.addAliasPlaceholder': 'Add alias...',
  'worldModel.entity.addAlias': 'Add',
  'worldModel.entity.attributes': 'Attributes',
  'worldModel.entity.addAttribute': '+ Add attribute',
  'worldModel.entity.column.name': 'Attribute',
  'worldModel.entity.column.surface': 'Surface',
  'worldModel.entity.column.truth': 'Truth',
  'worldModel.entity.column.visibility': 'Visible',
  'worldModel.entity.customTypePlaceholder': 'Custom type...',

  'worldModel.relationship.empty': 'Select an entity to view relationships',
  'worldModel.relationship.new': 'Create relationship',
  'worldModel.relationship.fromTo': ({ source, target }) => `From ${String(source ?? '')} to ${String(target ?? '')}`,
  'worldModel.relationship.selectTargetFallback': '(select a target entity)',
  'worldModel.relationship.searchTargetPlaceholder': 'Search target entities...',
  'worldModel.relationship.noMatchingTargets': 'No matching target entities',
  'worldModel.relationship.labelPlaceholder': 'Relationship label',

  'worldModel.system.new': '+ New system',
  'worldModel.system.back': '‹ Systems',
  'worldModel.system.delete': 'Delete system',
  'worldModel.system.deleteConfirm': 'Confirm delete?',
  'worldModel.system.searchPlaceholder': 'Search systems...',
  'worldModel.system.namePlaceholder': 'System name',
  'worldModel.system.unsupportedType': 'This system type cannot be edited right now. Check whether the data still needs migration.',
  'worldModel.system.rejectAllTitle': 'Reject all draft systems?',
  'worldModel.system.rejectAllDescription': ({ count }) => `This will delete ${String(count ?? 0)} draft systems.\nThis cannot be undone.`,
  'worldModel.system.rejectAllConfirm': 'Reject and delete',
  'worldModel.system.display.hierarchy': 'Hierarchy',
  'worldModel.system.display.timeline': 'Timeline',
  'worldModel.system.display.list': 'List',
  'worldModel.system.display.graph': 'Graph (read-only)',

  'worldModel.legacyGraph.notice': 'This is a legacy graph-based system. The current version keeps read compatibility only and no longer supports creating or editing graph structures. To keep maintaining it, migrate the data to relationships or to a list/hierarchy system.',
  'worldModel.legacyGraph.nodes': ({ count }) => `Nodes (${String(count ?? 0)})`,
  'worldModel.legacyGraph.edges': ({ count }) => `Edges (${String(count ?? 0)})`,
  'worldModel.legacyGraph.emptyNodes': 'No nodes to display.',
  'worldModel.legacyGraph.emptyEdges': 'No edges to display.',

  'worldModel.bootstrap.extractFromChapters': 'Extract from chapters',
  'worldModel.bootstrap.reextractDrafts': 'Re-extract drafts',
  'worldModel.bootstrap.failed': 'Run failed',
  'worldModel.bootstrap.completedIndexRefresh': 'Whole-book retrieval refreshed',
  'worldModel.bootstrap.summaryCounts': ({ entities, relationships }) => `${String(entities ?? 0)} entities · ${String(relationships ?? 0)} relationships`,
  'worldModel.bootstrap.confirmTitle': 'Dangerous action: re-extract chapter drafts',
  'worldModel.bootstrap.confirmDescription': 'Replace the current drafts extracted from chapters (while keeping confirmed data), then extract entities and relationships again.\nContinue?',
  'worldModel.bootstrap.confirmAction': 'Confirm re-extract',
  'worldModel.bootstrap.step.pending': 'Preparing',
  'worldModel.bootstrap.step.tokenizing': 'Tokenizing',
  'worldModel.bootstrap.step.extracting': 'Extracting candidates',
  'worldModel.bootstrap.step.windowing': 'Analyzing chapter links',
  'worldModel.bootstrap.step.refining': 'Refining with AI',
  'worldModel.bootstrap.noText': 'Upload chapter content first',
  'worldModel.bootstrap.triggerFailed': 'Action failed. Please try again.',

  'worldModel.windowIndex.bootstrap.preparingContent': 'Preparing whole-book content',
  'worldModel.windowIndex.bootstrap.organizingChapters': 'Organizing chapter content',
  'worldModel.windowIndex.bootstrap.ready': 'Ready to search clues across the whole book',
  'worldModel.windowIndex.bootstrap.pendingSync': 'Waiting to sync after chapter updates',
  'worldModel.windowIndex.bootstrap.missing': 'Whole-book content is still being prepared',
  'worldModel.windowIndex.bootstrap.failed': 'Whole-book retrieval is temporarily unavailable',
  'worldModel.windowIndex.copilot.preparingContent': 'Preparing whole-book content.',
  'worldModel.windowIndex.copilot.organizingContent': 'The chapters changed, so whole-book content is being organized; for now the app will fall back to recent chapters.',
  'worldModel.windowIndex.copilot.ready': 'Ready to search settings, characters, and clues across chapters.',
  'worldModel.windowIndex.copilot.pendingSync': 'The chapters changed, so whole-book content is syncing; for now the app will fall back to recent chapters.',
  'worldModel.windowIndex.copilot.missing': 'Whole-book content is still being prepared; for now the app will fall back to recent chapters.',
  'worldModel.windowIndex.copilot.failed': 'Whole-book content failed to organize for now; the app will fall back to recent chapters.',

  'worldModel.generate.title': 'Generate from setting text',
  'worldModel.generate.description': 'Paste world-setting text here, generate drafts, then review them in “Draft review”.',
  'worldModel.generate.placeholder': 'Paste world-setting text here (for example: world rules, factions, character relationships, power systems...)',
  'worldModel.generate.minLength': ({ count }) => `At least ${String(count ?? 0)} non-whitespace characters`,
  'worldModel.generate.tooLong': 'The input exceeds the limit',
  'worldModel.generate.submit': 'Generate',
  'worldModel.generate.submitting': 'Generating...',
  'worldModel.generate.importLink': 'Already have a worldpack file? Import it directly',
  'worldModel.generate.importing': 'Importing...',
  'worldModel.generate.inputInvalid': 'The input is invalid. Please check the length.',
  'worldModel.generate.serviceUnavailable': 'The AI service is unavailable. Check the model config or try again later.',
  'worldModel.generate.schemaInvalid': 'The AI response could not be parsed. Please try again.',
  'worldModel.generate.conflict': 'The generation conflicted with another change. Please try again.',
  'worldModel.generate.failed': 'Generation failed. Please try again.',
  'worldModel.generate.fileUnsupported': 'Unsupported file format. Please use a valid worldpack file.',
  'worldModel.generate.fileUnreadable': 'The file content could not be recognized. Please check the file format.',
  'worldModel.generate.validation.maxChars': ({ count }) => `At most ${String(count ?? 0)} characters`,
  'worldModel.generate.validation.minChars': ({ count }) => `Please enter at least ${String(count ?? 0)} non-whitespace characters`,

  'worldModel.worldpack.title': 'Import worldpack',
  'worldModel.worldpack.subtitle': 'Upload a worldpack file',
  'worldModel.worldpack.selectAndImport': 'Choose a file and import',
  'worldModel.worldpack.import': 'Import',
  'worldModel.worldpack.importing': 'Importing...',
  'worldModel.worldpack.completed': 'Worldpack import completed',
  'worldModel.worldpack.failed': 'Worldpack import failed. Please try again.',
  'worldModel.worldpack.fileUnsupported': 'Unsupported file format. Please use a valid worldpack file.',
  'worldModel.worldpack.fileUnreadable': 'The file content could not be recognized. Please check the file format.',

  'worldModel.draftReview.noMatches': 'No matching items',
  'worldModel.draftReview.noDrafts': 'No drafts yet',
  'worldModel.draftReview.viewAll': 'View all →',
  'worldModel.draftReview.rejectAndDelete': 'Reject and delete',
  'worldModel.draftReview.rejectAllTitle': ({ kind }) => `Reject all ${String(kind ?? '').toLowerCase()}?`,
  'worldModel.draftReview.rejectAllDescription': ({ count, kind }) => `This will delete ${String(count ?? 0)} draft ${String(kind ?? '').toLowerCase()}.\nThis cannot be undone.`,

  'worldModel.onboarding.title': 'Build the world model before you start writing',
  'worldModel.onboarding.description': 'You can generate drafts from setting text, or extract entities and relationships from uploaded chapters.',
  'worldModel.onboarding.generateTitle': 'Generate from setting text',
  'worldModel.onboarding.generateDescription': 'Paste world-setting text so AI can extract draft entities, relationships, and systems for you to confirm one by one.',
  'worldModel.onboarding.extractTitle': 'Extract from chapters',
  'worldModel.onboarding.extractDescription': 'Automatically extract draft entities and relationships from the chapters you already uploaded.',
  'worldModel.onboarding.dismiss': 'Go to the world-model page and add it later →',
  // -- Continuation Setup --
  'continuation.setup.basedOn': ({ chapter }) => `Continue from ${String(chapter ?? '')}`,
  'continuation.setup.charCount': ({ count }) => `${String(count ?? 0)} chars`,
  'continuation.setup.loadingChapter': 'Loading chapter content...',
  'continuation.setup.emptyChapter': 'No chapter content yet',
  'continuation.setup.title': 'Continuation settings',
  'continuation.setup.instruction': 'Continuation instruction (optional)',
  'continuation.setup.instructionPlaceholder': 'Describe the plot direction you want, or leave blank for free continuation',
  'continuation.setup.length': 'Continuation length',
  'continuation.setup.advancedSettings': 'Advanced settings',
  'continuation.setup.contextChapters': 'Context chapters',
  'continuation.setup.numVersions': 'Versions to generate',
  'continuation.setup.temperature': 'Temperature',
  'continuation.setup.generate': 'Generate continuation',

  // -- Continuation Results --
  'continuation.results.loading': 'Loading continuation results...',
  'continuation.results.retry': 'Retry',
  'continuation.results.back': 'Back',
  'continuation.results.noResults': 'No continuation results found. Please regenerate from the workspace.',
  'continuation.results.returnToWorkspace': 'Return to workspace',
  'continuation.results.quotaExhausted': 'Generation quota exhausted',
  'continuation.results.serviceBusy': 'The service is busy right now. Please try again later.',
  'continuation.results.requestFailed': ({ status }) => `Request failed (HTTP ${String(status ?? '')})`,
  'continuation.results.quotaFeedback': 'Submit feedback to earn extra generation quota and keep writing.',
  'continuation.results.submitFeedbackUnlock': 'Submit feedback, unlock quota',
  'continuation.results.feedbackAlreadyClaimed': 'Feedback quota already claimed. You can configure your own API Key in Settings to continue.',
  'continuation.results.goToSettings': 'Go to Settings',
  'continuation.results.badge': 'Continuation results',
  'continuation.results.continuationOf': ({ chapter }) => `continuation of ${String(chapter ?? '')}`,
  'continuation.results.generating': 'Generating',
  'continuation.results.adopt': 'Adopt this version',
  'continuation.results.regenerate': 'Regenerate',
  'continuation.results.exportAll': 'Export all',
  'continuation.results.version': ({ n }) => `Version ${String(n ?? '')}`,
  'continuation.results.injectionSummary': ({ entities, relationships, systems }) =>
    `Injection summary (${String(entities ?? 0)} entities, ${String(relationships ?? 0)} relationships, ${String(systems ?? 0)} systems)`,
  'continuation.results.emptyContent': 'No content yet',
  'continuation.results.exportVersionHeader': ({ n }) => `========== Version ${String(n ?? '')} ==========`,

  // -- Chapter Editor --
  'editor.undo': 'Undo',
  'editor.redo': 'Redo',
  'editor.driftWarning': 'Drift warnings',
  'editor.charCount': ({ count }) => `${String(count ?? 0)} chars`,
  'editor.cursorPosition': ({ para, col }) => `Para ${String(para ?? 0)} · Col ${String(col ?? 0)}`,
  'editor.autoSaved': 'Auto-saved',
  'editor.unsaved': 'Unsaved changes',
  'editor.save': 'Save',

  // -- Drift Warning Popover --
  'drift.unknownTerm': 'Unknown term',
  'drift.unknownNaming': 'Unknown naming',
  'drift.unknownDefault': 'Unknown term',
  'drift.dismiss': 'Dismiss',

  // -- Prose Warnings Panel --
  'prose.repeatedNgram': 'Repeated phrase',
  'prose.longParagraph': 'Long paragraph',
  'prose.abnormalSentenceLength': 'Long sentence',
  'prose.summaryTone': 'Summary tone',
  'prose.checkTitle': ({ count }) => `Prose quality check (${String(count ?? 0)} ${Number(count) === 1 ? 'issue' : 'issues'})`,
  'prose.itemCount': ({ count }) => `${String(count ?? 0)} ${Number(count) === 1 ? 'item' : 'items'}`,
  'prose.candidate': ({ n }) => `Candidate ${String(n ?? '')}`,

  // -- Studio Page --
  'studio.chapter.deleteConfirm': ({ chapter }) => `Delete ${String(chapter ?? '')}? This cannot be undone.`,
  'studio.chapter.editing': 'Editing',
  'studio.chapter.reading': 'Reading',
  'studio.chapter.titlePlaceholder': 'Enter chapter title',
  'studio.chapter.titleEditHint': 'Double-click to edit title',
  'studio.chapter.titleAddHint': 'Double-click to add title',
  'studio.header.workspace': 'Chapter workspace',
  'studio.header.selectChapter': 'Select chapter',
  'studio.actions.moreActions': 'More actions',
  'studio.actions.exportAllChapters': 'Export all chapters',
  'studio.loading': 'Loading...',
  'studio.novelNotFound': 'Novel not found',
  'studio.chapter.charCount': ({ count }) => `${String(count ?? 0)} chars`,
  'studio.chapter.updated': ({ time }) => `updated ${String(time ?? '')}`,
  'studio.chapter.edit': 'Edit',
  'studio.chapter.delete': 'Delete chapter',
} as const satisfies Record<keyof typeof novelZhMessages, UiMessageValue>

export const novelUiMessages = {
  zh: novelZhMessages,
  en: novelEnMessages,
} as const

registerUiMessages(novelUiMessages)
