"""Indexing primitives and services."""

from .builder import (
    ChapterText,
    build_window_index,
    compute_cooccurrence,
    detect_language,
    extract_candidates,
    get_tokenizer,
    load_common_words,
    tokenize_text,
)
from .lifecycle import (
    KNOWN_WINDOW_INDEX_STATUSES,
    WINDOW_INDEX_REBUILD_FAILED_MESSAGE,
    WindowIndexLifecycleSnapshot,
    WINDOW_INDEX_STATUS_FAILED,
    WINDOW_INDEX_STATUS_FRESH,
    WINDOW_INDEX_STATUS_MISSING,
    WINDOW_INDEX_STATUS_STALE,
    enqueue_window_index_rebuild_job,
    inspect_window_index_lifecycle,
    inspect_window_index_lifecycles,
    inspect_window_index_rebuild_job,
    inspect_window_index_rebuild_jobs,
    mark_window_index_build_failed,
    mark_window_index_build_succeeded,
    mark_window_index_inputs_changed,
    mark_window_index_missing,
    normalize_window_index_status,
    resolve_window_index_target_revision,
    run_window_index_rebuild_for_latest_revision,
)
from .rebuild import WindowIndexArtifacts, build_window_index_artifacts, load_chapter_texts
from .window_index import NovelIndex, WindowRef

__all__ = [
    "ChapterText",
    "NovelIndex",
    "WindowRef",
    "WindowIndexArtifacts",
    "WindowIndexLifecycleSnapshot",
    "WINDOW_INDEX_REBUILD_FAILED_MESSAGE",
    "WINDOW_INDEX_STATUS_FAILED",
    "WINDOW_INDEX_STATUS_FRESH",
    "WINDOW_INDEX_STATUS_MISSING",
    "WINDOW_INDEX_STATUS_STALE",
    "build_window_index",
    "build_window_index_artifacts",
    "compute_cooccurrence",
    "detect_language",
    "extract_candidates",
    "get_tokenizer",
    "KNOWN_WINDOW_INDEX_STATUSES",
    "load_common_words",
    "load_chapter_texts",
    "enqueue_window_index_rebuild_job",
    "inspect_window_index_lifecycle",
    "inspect_window_index_lifecycles",
    "inspect_window_index_rebuild_job",
    "inspect_window_index_rebuild_jobs",
    "mark_window_index_build_failed",
    "mark_window_index_build_succeeded",
    "mark_window_index_inputs_changed",
    "mark_window_index_missing",
    "normalize_window_index_status",
    "resolve_window_index_target_revision",
    "run_window_index_rebuild_for_latest_revision",
    "tokenize_text",
]
